engines:
  duplication:
    enabled: true
    exclude_paths:
      - little_brother/test/**
      - alembic/versions/**

exclude_paths:
  - 'little_brother/templates/**'
  - 'little_brother/static/contrib/**'
  - '**/*.md'
